### ISSUE TITLE
Is not able to find *.proto if ran from outside of the directory

### ISSUE THREAD

**Issue by binodluitel** [pseudomuto/protoc-gen-doc#296]
```
protoc -I=/path/to/proto/ --go_out=plugins=grpc:/path/to/protos --doc_out=markdown,myproto.md:/path/to/protos /path/to/proto/myproto.proto
```

Results in:
```
--doc_out: myproto.proto: myproto.proto: No such file or directory
```

This works fine and generates *.pb.go without any problem
```
protoc -I=/path/to/proto/ --go_out=plugins=grpc:/path/to/protos --doc_out=markdown,myproto.md:/path/to/protos
```

if I cd into directory where *.proto is and run
```
protoc -I=/path/to/proto/ --go_out=plugins=grpc:/path/to/protos --doc_out=markdown,myproto.md:/path/to/protos /path/to/proto/myproto.proto
```

works fine as well

**Comment by samipshah** [comment]
having the exact same issue.

**Comment by panzerfahrer** [comment]
@pseudomuto Could this be resolved with the go port / v1.0.0 ?

**Comment by dshikhaleev** [comment]
Tried to use protoc-gen-doc from protobuf gradle plugin. I see two issues there
1. protoc-gen-doc can't find photo files
2. generated doc is placed into src-gen directory. 

I think these are related to this defect. I'll give it another try when issue is fixed.

**Comment by pseudomuto** [comment]
Hey guys, is this still an issue with the updated codebase?

**Comment by panzerfahrer** [comment]
With v1.0.0 its working for me.

Like @dshikhaleev, I'm also using the protobuf gradle plugin: with a pretty-much default config it's working well so far.

**Comment by pseudomuto** [comment]
Excellent! Thanks so much for testing it out @panzerfahrer! I'm going to close this issue. @dshikhaleev feel free to reopen if necessary

**Comment by binodluitel** [comment]
Working for me as well. Thanks for addressing

**Comment by slackfarmer** [comment]
Where can I find gradle examples that use this plugin?

I am currently using the gradle google protobuf plugin

`com.google.protobuf:protobuf-gradle-plugin:0.8.3`
