### ISSUE TITLE
Enum values seem to be enumerated, rather than taking the value defined

### ISSUE THREAD

**Issue by whgibbo** [pseudomuto/protoc-gen-doc#311]
Hi,
Was wondering if anybody has come across this problem:

> option optimize_for=LITE_RUNTIME;
> 
> package com.test;
> 
> enum ErrorCode {
>     Value1              = 0;
>     Value2              = 2;
>     Value3              = 115;   
> }
> 

When executing this:

> protoc32 --docbook_out=.\doc --plugin=docbook_out=protoc-gen-doc.exe --proto_path=.\protobuf .\protobuf\Error.proto

The xml file generate has the wrong values for the enums :(

Any thoughts ?

**Comment by pseudomuto** [comment]
Hey @whgibbo, can you see if this works correctly for you using the 1.0 beta?

# Testing With Docker

```
docker pull pseudomuto/protoc-gen-doc
docker run --rm \
  -v $(pwd)/protobuf:/protos:ro \
  -v $(pwd)/doc:/out \
  protoc-gen-doc --doc_opt=dockbook,doc.xml /protos/Error.proto
```

# Testing With the Executable

* Go to https://github.com/pseudomuto/protoc-gen-doc/releases/tag/v1.0.0-beta
* Download the windows build and extract it
* Put `protoc-gen-doc.exe` on your path

At this point, you should be able to run the same command you have above.
