### ISSUE TITLE
Get open md: no such file or directory when generating markdown using the docker container

### ISSUE THREAD

**Issue by jrabary** [pseudomuto/protoc-gen-doc#329]
Hi I'm trying to generate a markdown documentation of my .proto. When I add the `--doc_opt=md,doc.md` option I get the following error ` open md: no such file or directory`.
I'm using the docker image on macos X.

**Comment by pseudomuto** [comment]
Can you paste the entire command you're using? Looks like `md` is being used as a format, but it should be `markdown`. For example:

```
docker run --rm \
  -v $(pwd)/doc:/out \
  -v $(pwd)/proto:/protos \
  pseudomuto/protoc-gen-doc --doc_opt=markdown,doc.md
```

**Comment by pseudomuto** [comment]
I'm going to assume that the md vs markdown was the issue here. Please feel free to reopen if that's not the case.
