### ISSUE TITLE
Update Test Fixtures to test enhancements

### ISSUE THREAD

**Issue by timleung22** [pseudomuto/protoc-gen-doc#331]
I am trying to see how options are being handled, and was trying to run the proto3_test.go with Booking.proto and Vehicle.proto that have my changes.  Unfortunately my changes to the proto was not being taken into account because the test uses the content inside generator_request.dat.  What is the proper way to update generator_request.dat with my modified protos

**Comment by pseudomuto** [comment]
Hey @timleung22, you should be able to update that with `make generate`. Feel free to reopen if this doesn't work for you.
