### ISSUE TITLE
Add oneOf support

### ISSUE THREAD

**Issue by jason-fox** [pseudomuto/protoc-gen-doc#333]
In our proto files we use the `oneof`  keyword and we have noticed that this is currently ignored in the generated outputs. Our documentation team would like to see `oneof` support added to the tool.

To generate `oneOf` support  for the  0.96 release I had added the following QT code to the `message` generation (line 346 onwards)

```
// Add basic info.
field["field_name"] = QString::fromStdString(fieldDescriptor->name());
field["field_description"] = description;
field["field_label"] = labelName(fieldDescriptor->label());
field["field_default_value"] = defaultValue(fieldDescriptor);
if (fieldDescriptor->containing_oneof()){
    field["field_one_of"] = QString::fromStdString(fieldDescriptor->containing_oneof()->name());
    field["field_one_of_description"] = descriptionOf(fieldDescriptor->containing_oneof(), excluded);
}
```

Since then I see that the code has been ported to GO, and I have another have been working on adding the equivalent code to the 1.0.0 release.

Would you like to examine a PR for making this happen?

**Comment by pseudomuto** [comment]
Hey @jason-fox, I'd definitely be interested in a PR to add oneOf support!

**Comment by Falco20019** [comment]
I added my patches as base in the existing PR https://github.com/pseudomuto/protoc-gen-doc/pull/336 Didn't have time to do a proper PR and add tests. Sorry for that :(

**Comment by jorgheymans** [comment]
any updates on this, is it going to get done at some point ?

**Comment by amrhassan** [comment]
It would be excellent to have this.

**Comment by marcosrmendezthd** [comment]
any progress on this?

**Comment by jason-fox** [comment]
No resolution in five years. Closing.
