### ISSUE TITLE
scrubComment should not Trim leading asterisk when using C++ style comments

### ISSUE THREAD

**Issue by jason-fox** [pseudomuto/protoc-gen-doc#338]
**The problem**

Consider the following comment lines ( taken from [any.proto line 132-134](https://github.com/google/protobuf/blob/master/src/google/protobuf/any.proto#L132))

```c++
// ... definitions as follows:
//
// * If no scheme is provided, `https` is assumed.
```

The description is currently rendered as follows:

```json
 `... definitions as follows:\n\nIf no scheme is provided
```

The leading asterisk `*` (a markdown bullet point) has been stripped from the description field.

**The reason**

The culprit is the  [scrubComment function - lines 53-55](https://github.com/pseudomuto/protoc-gen-doc/blob/master/parser/comments.go#L53)

```go
for idx, line := range lines {
	lines[idx] = strings.Trim(line, " /\n*")
}
```
This is greedily removing asterisks at the the start and end of a comment line - in order to handle `/* ... */`  C style comments.

**Potential Fix**

Handling `/*` is still valid of course, but adding the following pseudo code logic would allow for proper markdown comments when using the alternative  C++ double slash `//` comment syntax:

1) `strings.Trim()` **all** leading and trailing spaces and new line `\n` chars

```go
  strings.Trim(line, " \n")
```

2) If line starts with `//`  - `strings.Trim()`  slashes and space again

```go
  strings.Trim(line, " /")
```

3) **However**  if line doesn't start with `//` - `strings.Trim()`  slashes and space and asterisk 
 
```go
  strings.Trim(line, " /*")
```
**But it's not so simple**

Looking at [descriptor.pb.go line 1730-1733](https://github.com/golang/protobuf/blob/master/protoc-gen-go/descriptor/descriptor.pb.go#L1730-L1733))

```c++
// Only the comment content is provided; comment markers (e.g. //) are
// stripped out.  For block comments, leading whitespace and an asterisk
// will be stripped from the beginning of each line other than the first.
// Newlines are included in the output.
```

 I can see that comment markers are **already** handled and stripped I guess `scrubComment()` is currently dealing with such problems as:

```java
/**
* Java Doc style comment
*/
```

```java
/*******************************
* Java Doc style comment *
********************************/
```

```c++
/// C Sharp style comment
```

```c++
//////////////////////////
// Decorated block
//////////////////////////
```

**Comment by jason-fox** [comment]
**Fix using regular Expressions**

In order to strip asterisks `*` **only** at the start/end of line and **only**  if not preceded by whitespace, we're going to have to  replace substrings using regular expressions not `Trim`. 

This is the  change I have so far :

```go
import (
	"strings"
	"regexp"
)

func scrubComment(s string) string {
	var rePrefix = regexp.MustCompile(`^/*(\**|/*)(\s+|$)`)
	var reSuffix = regexp.MustCompile(`\s+(\**|/*)$`)
	lines := strings.Split(s, "\n")

	for idx, line := range lines {
		line = strings.TrimRight(line, " /\n")
		line = rePrefix.ReplaceAllString(line, "")
		line = reSuffix.ReplaceAllString(line, "")
		lines[idx] = strings.TrimLeft(line, " \n")
	}

	return strings.Trim(strings.Join(lines, "\n"), "\n")
}
```

I'll try to elaborate some test scenarios and create another PR.

**Comment by pseudomuto** [comment]
Your proposal sounds good to me! PRs are welcome :smile:

**Comment by jason-fox** [comment]
No response in five years. Closing.
