### ISSUE TITLE
Skip dependencies

### ISSUE THREAD

**Issue by db80** [pseudomuto/protoc-gen-doc#341]
Hi There!

Is it possible to skip the generation of the docs for the dependencies?
example:

`import "google/protobuf/timestamp.proto"; //@exclude`

Thanks.

**Comment by pseudomuto** [comment]
Hey @db80, I recently updated the parsing code and think this issue might have been solved in the process. 

Would you be able to verify if this is still an issue using master?

**Comment by db80** [comment]
it works like a charm 👍 
Thanks.

**Comment by pseudomuto** [comment]
Sweet! Thanks for testing this out!
