### ISSUE TITLE
Bad link in HTML output

### ISSUE THREAD

**Issue by cly753** [pseudomuto/protoc-gen-doc#346]
Hi All,

The link in the HTML seems wrong if it refers to the message in another proto package.

For example, I have two proto sources:

```
$ ls
a.proto b.proto

$ cat a.proto 
package A;

message MsgA {

}

$ cat b.proto 
import "a.proto";

message MsgB {
    optional A.MsgA a = 1;
}
```

and here is my protoc and protoc-gen-doc versions:
```
$ protoc --version
libprotoc 3.5.0

$ go get -u github.com/pseudomuto/protoc-gen-doc/cmd/...

$ protoc-gen-doc --version
protoc-gen-doc version 1.0.0
```

If I invoke the plugin by
```
$ protoc --doc_out=html,index.html:$(pwd) *.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: a.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: b.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)

$ ls
a.proto    b.proto    index.html
```

In the `index.html` contains 

```
<div class="file-heading">
    <h2 id="a.proto">a.proto</h2><a href="#title">Top</a>
</div>
<p></p>


<h3 id="A.MsgA">MsgA</h3>
<p></p>


<div class="file-heading">
    <h2 id="b.proto">b.proto</h2><a href="#title">Top</a>
</div>
<p></p>


<h3 id=".MsgB">MsgB</h3>
<p></p>


<table class="field-table">
    <thead>
    <tr>
        <td>Field</td>
        <td>Type</td>
        <td>Label</td>
        <td>Description</td>
    </tr>
    </thead>
    <tbody>

    <tr>
        <td>a</td>
        <td><a href="#..A.MsgA">.A.MsgA</a></td>
        <td>optional</td>
        <td><p></p></td>
    </tr>

    </tbody>
</table>
```

You can see the correct link to `MsgA` is `#A.MsgA`. However, the link to `MsgA` in `MsgB` is `<a href="#..A.MsgA">`. There is two extra dots (`..`) in the link.

May I know how I can get the correct link between message definitions?

Thanks in advance!

**Comment by pseudomuto** [comment]
Hey @cly753! 

I recently updated the parsing code on master. I think I might have solved this issue by accident :smile:

Here's how I tested:

**test_dir/a.proto**
```protobuf
syntax = "proto3";

package A;

message MsgA {}
```

**test_dir/b.proto**
```protobuf
syntax = "proto3";

import "a.proto";

message MsgB {
  A.MsgA a = 1;
}
```

Then I ran (after `make build`) the following to generate the HTML:

```
protoc --plugin=protoc-gen-go -Itest_dir \
  --doc_out=test_dir --doc_opt=html,index.html \
  test_dir/*.proto
```

When I checked the resulting html file (line 251 in my case), the link looked like this:

```html
<td><a href="#A.MsgA">A.MsgA</a></td>
```

Can you verify on master to see if this is working as expected?

**Comment by cly753** [comment]
Hi @pseudomuto 

Cool it works now!

**Comment by CptanPanic** [comment]
I am using the prebuilt release and have this same problem.  Is it possible to get a new release built that includes this fix?

**Comment by pseudomuto** [comment]
@CptanPanic here you go! https://github.com/pseudomuto/protoc-gen-doc/releases/tag/v1.1.0

**Comment by CptanPanic** [comment]
Ok so I tried this release but still doesn't work for me, and where before the link had too many '.' such as <td><a href="#..ArmType">ArmType</a></td> when it should only have 1x '.', it now doesn't have any '.' as <td><a href="#ArmType">ArmType</a></td> so it doesn't work.  If I manually add the '.' to URL it works.

**Comment by pseudomuto** [comment]
I don't know what ArmType is. Can you post a proto and the resulting invalid HTML?

**Comment by CptanPanic** [comment]
Attached is example proto and result html file.  Note ArmType is submessage of TestMessage.  And note that if you click on ArmType link in description of TestMessage nothing happens because anchor is wrong, see line 242 of .html.  

[Downloads.zip](https://github.com/pseudomuto/protoc-gen-doc/files/1808282/Downloads.zip)

Generated with 

> protoc --plugin=/opt/protoc-gen-doc --doc_out=./doc --doc_opt=html,index.html test.proto

**Comment by CptanPanic** [comment]
@pseudomuto Any updates on this issue?  Should I open a new issue to keep track of this?

**Comment by pseudomuto** [comment]
@CptanPanic sorry for the delay, it's a hectic week. I think a new issue is a great idea!

**Comment by MaggieLeber** [comment]
Breadcrumb: https://github.com/pseudomuto/protoc-gen-doc/issues/351
