### ISSUE TITLE
docker examples do not work

### ISSUE THREAD

**Issue by maxthomas** [pseudomuto/protoc-gen-doc#356]
cloning the repo freshly, `cd`ing into it and trying to docker examples does not work

this is on linux (centOS)

```
centos@max-pre-key-snapper-dos: /home/centos
➜   go get -u github.com/pseudomuto/protoc-gen-doc
centos@max-pre-key-snapper-dos: /home/centos
➜   cd $GOSRC/github.com/pseudomuto/protoc-gen-doc
centos@max-pre-key-snapper-dos: /home/centos/go/src/github.com/pseudomuto/protoc-gen-doc git:(master)
➜   pwd
/home/centos/go/src/github.com/pseudomuto/protoc-gen-doc
centos@max-pre-key-snapper-dos: /home/centos/go/src/github.com/pseudomuto/protoc-gen-doc git:(master)
➜   docker run --rm \
>   -v $(pwd)/examples/doc:/out \
>   -v $(pwd)/examples/proto:/protos \
>   pseudomuto/protoc-gen-doc
protos/*.proto: No such file or directory
```

**Comment by pseudomuto** [comment]
Hey @maxthomas, I'm sorry the examples aren't working for you.

I noticed that there was no attempt to download the docker image there. Do you have a specific version already pulled?

I deleted all images on my system and was able to run the following successfully. Can you give it a shot?

I used `docker images -a | grep "protoc-gen-doc" | awk '{print $3}' | xargs docker rmi` to remove the local images and then ran:

```
➜  protoc-gen-doc git:(master) docker run --rm \
-v $(pwd)/examples/doc:/out \
-v $(pwd)/examples/proto:/protos \
pseudomuto/protoc-gen-doc
Unable to find image 'pseudomuto/protoc-gen-doc:latest' locally
latest: Pulling from pseudomuto/protoc-gen-doc
d2ca7eff5948: Already exists
755ec9c7b09f: Pull complete
bee8587ff7c9: Pull complete
42f587175cf1: Pull complete
d922ee730c67: Pull complete
Digest: sha256:c6af7507d1796dae119a64f6795877457f0d450de9e1e5749aa19a478f3f711e
Status: Downloaded newer image for pseudomuto/protoc-gen-doc:latest
```

**Comment by quanyi8** [comment]
Not working for me: I just installed docker and pulled the image (pseudomuto/protoc-gen-doc), and run following command and gives error "protos/*.proto: No such file or directory". 

docker run --rm \
  -v $(pwd)/examples/doc:/out \
  -v $(pwd)/examples/proto:/protos \
  pseudomuto/protoc-gen-doc
