### ISSUE TITLE
Using glob for proto files

### ISSUE THREAD

**Issue by jzeferino** [pseudomuto/protoc-gen-doc#380]
It is possible to use glob sintax to reference the proto files?

`docker run --rm -v /home/work/proto/**/:/protos -v /home/work/a:/out pseudomuto/protoc-gen-doc --doc_opt=markdown,docs.md`

**Comment by twslankard** [comment]
Any luck with this, @jzeferino? I'm trying to find out how to get the tool to traverse the directory.

**Comment by jzeferino** [comment]
Well, what I ended up doing was to flatten the proto files and after that run the doc generation.

I was on a mac so I did this to flatten the protos:

```
mkdir ./proto_flat
find ./proto -name '*.proto' -exec mv {} ./proto_flat \;
```

And then:

`docker run --rm -v /home/work/proto_flat -v /home/work/doc:/out pseudomuto/protoc-gen-doc --doc_opt=markdown,docs.md`

**Comment by anavgagneja** [comment]
I tried the flattening approach and found that it broke all my import statements that reference other protos by directory structure... any other ideas? I see a couple PRs for this that are still open.

**Comment by Falco20019** [comment]
I just mounted the adjusted script from #437 into the container (replacing it) to get the logic fixed without waiting for the PR to be merged. I just pinged the maintainer as it seem to got lost.
