### ISSUE TITLE
release 1.3.1 for module support

### ISSUE THREAD

**Issue by carnott-snap** [pseudomuto/protoc-gen-doc#404]
I see that you merged a `go.mod` back in 0b08327, but have yet to release a tag that allows us to consume this change. Could this be rectified?

**Comment by tmc** [comment]
ping here.

**Comment by mortenlocka** [comment]
Any chance for a new release? Would like support for envoyproxy (lyft) validation framework

**Comment by carnott-snap** [comment]
@pseudomuto any update on this?

**Comment by pseudomuto** [comment]
Apologies for the delay. v1.3.1 is now available!
