### ISSUE TITLE
Envoyproxy validated fields not present in generated html (v.1.3.1)

### ISSUE THREAD

**Issue by mortenlocka** [pseudomuto/protoc-gen-doc#414]
Hi,
Using protoc-gen-doc 1.3.1.

`protoc --plugin=protoc-gen-doc=./protoc-gen-doc --doc_out=./doc --doc_opt=html,index.html Customer.proto`

On the following file:
https://github.com/pseudomuto/protoc-gen-doc/blob/master/examples/proto/Customer.proto

With the imported github.com/envoyproxy/protoc-gen-validate/validate/validate.proto in a folder structure next to Customer.proto.

Does not generate the “Validated Fields” element in the generated html.

Is it something I am missing? A feature toggle, an import etc?

**Comment by yukpiz** [comment]
Hi

I have the same problem.
The output example.html appears to output validator.field, but does not output validate.rules.

*example.html*
https://gist.github.com/yukpiz/6e320a24cc5e4373388f434b1185104c

I tried using a custom template, but nothing is included in ``Message.FieldOptions``

```
pseudomuto/protoc-gen-doc@v1.3.1
envoyproxy/protoc-gen-validate@0.3.0
protoc@3.6.1
```

**Comment by zetaron** [comment]
I have been experiencing the same issue and was able to track it down to breaking changes in the protocol. When you provide a downgraded version ([`v.0.0.14`](https://github.com/envoyproxy/protoc-gen-validate/tree/v0.0.14)) of the `envoyproxy/protoc-gen-validate/validate/validate.proto` it works - with respect to the features that where available at the time.

Maybe updating the `go.mod` file to the current version [`v0.3.0-java`](https://github.com/envoyproxy/protoc-gen-validate/tree/v0.3.0-java).
