### ISSUE TITLE
Protobuf 3 Optional using Docker Image

### ISSUE THREAD

**Issue by Awbmilne** [pseudomuto/protoc-gen-doc#442]
I havent been able to find a way to pass the `--experimental_allow_proto3_optional` flag to the docker image. I would like to use this image for CI, but installing the app with Go is just more difficult and feels unnecessary.

Is there a way to accomplish this that i'm missing? Or is this not possible?

**Comment by wespen** [comment]
Im on it already.
Once all packages support it Ill do MR.
(Opened up new issue in all affected repos)

Wating for proto3 optional support in packages:
protoc-gen-validate (https://github.com/envoyproxy/protoc-gen-validate/issues/431)
protoc-gen-micro (https://github.com/micro/micro/issues/1766)
protoc-gen-rbi (https://github.com/coinbase/protoc-gen-rbi/issues/24)
protoc-gen-gogofast (https://github.com/gogo/protobuf/issues/713)

**Comment by panter-dsd** [comment]
#464 there is an outdated version of protoc

**Comment by davidjlynn** [comment]
@Awbmilne With the new version [v1.5.1](https://github.com/pseudomuto/protoc-gen-doc/releases/tag/v1.5.1) there is no need to pass the experimental flag, optional is supported by default.
This can be closed and the new version used.
