### ISSUE TITLE
markdown anchors have invalid characters

### ISSUE THREAD

**Issue by derlin** [pseudomuto/protoc-gen-doc#457]
The markdown anchors (inside `<a name="..">` and in the TOC contain special characters such as `.` and `/` that are not compatible with BitBucket and some other tools. It would be great to sanitize the anchors, by replacing any slash with `_` and any special character with `-`. 

For example, given a proto `com.example.test.Example`, the generated anchor would be:
```html
<a name="com-example-test-example"></a>
```
And for a file com/example/test/v1/example.proto:
```html
<a name="com_example_test_v1_example-proto">
```

**Comment by pseudomuto** [comment]
Closed via #460
