### ISSUE TITLE
Separate the grpc services and messages in the generated document

### ISSUE THREAD

**Issue by seeflood** [pseudomuto/protoc-gen-doc#465]
**What would you like to be added**:
Separate the grpc services and messages to make the generated document more readable.

**Why is this needed**:
Currently a [generated document with a service and lots of messages](https://github.com/mosn/layotto/blob/main/docs/en/api_reference/api_reference_v1.md) is not readable enough. The grpc services and request/response messages are mixed without highlight:
![image](https://user-images.githubusercontent.com/26001097/137937987-5fa6a412-b22e-4c20-8576-8fc82c1189b1.png)

Can we seperate them to make the doc more readable?

**Comment by horacimacias** [comment]
you should be able to achieve this by using a custom template.
For example, instead of this
```jinja
## Table of Contents
{{range .Files}}{{$file_name := .Name}}
- [{{.Name}}](#{{.Name}})
  {{- if .Messages }}
  {{range .Messages}}  - [{{.LongName}}](#{{.FullName}})
  {{end}}
  {{- end -}}
  {{- if .Enums }}
  {{range .Enums}}  - [{{.LongName}}](#{{.FullName}})
  {{end}}
  {{- end -}}
  {{- if .Extensions }}
  {{range .Extensions}}  - [File-level Extensions](#{{$file_name}}-extensions)
  {{end}}
  {{- end -}}
  {{- if .Services }}
  {{range .Services}}  - [{{.Name}}](#{{.FullName}})
  {{end}}
  {{- end -}}
{{end}}
```

just put the services, or all services first then all models, or whatever you find most interesting.
In my case I'm putting only the services:
```jinja
## Table of Contents
{{range .Files}}{{$file_name := .Name}}
- [{{.Name}}](#{{.Name}})
  {{range .Services}}  - [{{.Name}}](#{{.FullName}})
  {{end}}
{{end}}

```

**Comment by horacimacias** [comment]
...of course the same applies to the template used for html which looks like is the output you're using
