### ISSUE TITLE
failed to run ` go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc`

### ISSUE THREAD

**Issue by rise0chen** [pseudomuto/protoc-gen-doc#531]
![image](https://github.com/pseudomuto/protoc-gen-doc/assets/12853908/01499eb3-0280-4baf-be68-f8e06e1ff9aa)

**Comment by fmg-ryandunbar** [comment]
You can work around this using `go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest`
