### ISSUE TITLE
Add homebrew support

### ISSUE THREAD

**Issue by ebenoist** [pseudomuto/protoc-gen-doc#76]
@estan this package is fantastic, but I'd love to make it a bit easier to install for folks using OS X. I've written a few homebrew formulas before, would one for protoc-gen-doc be of interest? Let me know!

**Comment by murph0** [comment]
Yes, I'd vote for that.

**Comment by estan** [comment]
Absolutely, I'd welcome that very much. Since I don't have a Mac, it'd be great if you could have a go at that (quite a chore to do it all via Travis CI).

**Comment by ebenoist** [comment]
Sounds good. I'll see if I can't whip something together this weekend. It's usually pretty straightforward.

**Comment by ebenoist** [comment]
First pass seems to work well

https://github.com/ebenoist/homebrew-protoc-gen-doc

I was a bit creative about how to "test" that the install worked. I'm open to some suggestions there. To move this forward we would either need to submit this to homebrew core or you can simply create your own tap for this package as I've done. Let me know how you want to move forward.

**Comment by estan** [comment]
Excellent. Let's submit your repo.

For testing, since there's no unit tests, what I did on Travis was just:

https://github.com/estan/protoc-gen-doc/blob/master/.travis.yml#L48-L53

Maybe that could be done on Homebrew too, using the installed version? You could skip the PDF output though, since that requires installing FOP, and just `rm doc/*.docbook doc/*.html doc/*.md` instead of `make clean`.

**Comment by estan** [comment]
Was this ever submitted to Homebrew?

**Comment by estan** [comment]
Please see my recent addition to the README.md, copied below. My sincerest apologies for this.

```
To all users of `protoc-gen-doc`: This project is now unmaintained and
seeking a new maintainer. The reason for this is two-fold:

1. I'm not using Protocol Buffers myself anymore, and haven't done so
   for years.

2. I'm too busy with work and other projects to keep developing
   the tool, deal with feature requests and PRs.

Too all those who have outstanding pull requests and/or issues filed:
I'm really sorry, and thank you so much for your contributions, but I
simply don't have time for the project anymore, even if it is quite
low-maintenance.

Are you a user of `protoc-gen-doc` who feel you could take over? Great!
Please get in touch with me privately and we can discuss how to best
proceed (GitHub forking and transferring of Travis CI / AppVeyor / Open
Build Service accounts). The code is quite simple and only moderate C++
skills and some familiarity with Qt is needed.

Again, to all users: I'm sorry for this inconvenience, but it would be
dishonest of me to continue claiming maintainership of this project
when I don't have the time anymore.
```

**Comment by samipshah** [comment]
brew tap ebenoist/protoc-gen-doc
brew install protoc-gen-doc

this commands work.
